apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-10T12:03:29Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "6030"
  uid: b87530e6-86fe-4f41-a82b-35dc63e1984b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.200.192
  clusterIPs:
  - 10.108.200.192
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30970
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
